name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UV_PROJECT_ENVIRONMENT: .venv
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.12"

      - name: Create virtual environment
        run: uv venv --python 3.12

      - name: Install project
        run: uv pip install -e '.[mesher]' pytest

      - name: Run pytest
        run: uv run pytest


  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    environment: pypi
    env:
      UV_PROJECT_ENVIRONMENT: .venv
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.12"

      - name: Create virtual environment
        run: uv venv --python 3.12

      - name: Ensure PyPI token
        shell: bash
        run: |
          TOKEN="${PYPI_API_TOKEN:-${PYPI_TOKEN:-}}"
          if [ -z "$TOKEN" ]; then
            echo "PYPI_API_TOKEN or PYPI_TOKEN secret not provided" >&2
            exit 1
          fi
          echo "PYPI_API_TOKEN=$TOKEN" >> "$GITHUB_ENV"

      - name: Load .env if present
        if: hashFiles('.env') != ''
        shell: bash
        run: |
          set -a
          source .env
          set +a
          if [ -n "${PYPI_API_TOKEN:-}" ]; then
            echo "PYPI_API_TOKEN=$PYPI_API_TOKEN" >> "$GITHUB_ENV"
          fi

      - name: Install build tooling
        run: uv pip install twine

      - name: Build wheel and sdist
        run: uv build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ env.PYPI_API_TOKEN }}
        run: uv run twine upload --skip-existing dist/*
